mysql:
  dbUrl: 192.168.100.23
  dbName: resico-invoice-dev2
  username: dev
  password: Resico@dev



wx:
  office:
    appId: wxbb2b0c04e0658377
    secret: 600877b09a45203618f4504c8cae7490
    token: 56_eGoZ86m59iFp3kVijYyxGdRlyxM9H-tl08FLvD0R6KIu2wj_LeEncwqQPgIP-S54UdbDKp26iWZ343lvAEruzB0Go2ByAM_jcjToGvF7bNE5uTfo38WJ5ypJAXeFzqYkGq3XTezhm1axCUnPGZUcAIAWPK